[package]
name = "fm"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting.workspace = true
cfg-if.workspace = true

# Comment the [target] line if you need to debug the macro expansion
[target.'cfg(target_arch = "wasm32")'.dependencies]
wit-bindgen-guest-rust.workspace = true

[dev-dependencies]
tempfile.workspace = true
