[package]
name = "noir_nd_stdlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
noir_nd = { path = "../noir_nd" }
wasm-bindgen = "*"
getrandom = { version = "0.2.4", features = ["js"] }

[dev-dependencies]
hex = "*"
