[package]
name = "nargo"
description = "Noir's package manager"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
acvm.workspace = true
noirc_abi.workspace = true
noirc_driver.workspace = true
toml.workspace = true
serde.workspace = true
thiserror.workspace = true
base64 = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
serde-big-array = { version = "0.5.1", optional = true }

[features]
default = []
bb_js = [
    "dep:base64",
    "dep:flate2",
    "dep:serde-big-array"
]
