[package]
name = "nargo"
description = "Noir's package manager"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
acvm.workspace = true
noirc_abi.workspace = true
noirc_driver.workspace = true
toml.workspace = true
serde.workspace = true
thiserror.workspace = true
# These three dependencies below are only needed to maintain the correct serialization for bb.js
base64 = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
serde-big-array = { version = "0.5.1", optional = true }
# Backend only needed by bb.js
acvm-backend-barretenberg = { optional = true, version = "0.3.0", default-features = false }

[features]
default = []
bb_js = [
    "dep:base64",
    "dep:flate2",
    "dep:serde-big-array",
    "acvm-backend-barretenberg/native"
]
