[package]
name = "noir_lsp_wasm"
description = "Language server for Noir compiled to WASI"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
noir_lsp.workspace = true
tower.workspace = true
futures = { version = "0.3.28", default-features = false, features = ["async-await", "std", "executor"] }
async-lsp = { workspace = true, features = ["omni-trait", "stdio", "async-io"] }
async-io = "2"
