[package]
name = "noir_nd"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noir_field = { path = "../noir_field", default-features = false }
libloading = "*"

# WASM dependencies
wasmer-wasi = "1.0.1"

wasmer = "1.0.1"
# wasmer-compiler-llvm = "1.0.1"
wasmer-engine-native = "1.0.1"
wasmer-engine-jit = "1.0.1"
wasmer-cache = "1.0.1"

[dev-dependencies]
tempdir = "*"

[features]
default = ["bn254"]
bn254 = ["noir_field/bn254"]
