[package]
name = "parser-fuzz-target"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
noirc_frontend.workspace = true
afl = "*"
