name: "Labeler"
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled

permissions:
  pull-requests: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.6
        # We continue-on-error because the action is buggy and tries to remove labels when they don't exist
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0

      - name: Set workflowId environment variable
        id: set_workflow_id
        run: |
          if [[ "${{ github.event.action }}" == "labeled" ]]; then
            echo "workflowId=new-migrated-issue.yml" >> $GITHUB_ENV
          else
            echo "workflowId=delete-migrated-issue.yml" >> $GITHUB_ENV
          fi

      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1 
        with: 
          workflow: ${{ env.workflowId }}
          repo: noir-lang/docs
          ref: master 
          token: ${{ secrets.GITHUB_TOKEN }} 
          inputs: '{ "pr_number": "${{ github.event.pull_request.number }}" }'
