name: Publish Nix Package

on:
  workflow_dispatch:
    inputs:
      noir-ref:
        description: The noir reference to checkout
        required: true
      package-name:
        description: The Nix package name to build
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CACHED_PATH: /tmp/nix-cache

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: "noir-lang/noir"
          ref: ${{ inputs.noir-ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 18.15

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build packages
        run: |
          yarn
          yarn build

      - name: Build Nix package
        run: nix build .#${{ inputs.package-name }}

      - name: Discover Build Output Path
        run: echo "BUILD_OUTPUT_PATH=$(readlink -f ./result/${{ inputs.package-name }})" >> $GITHUB_ENV

      - name: Copy Build Output to Temporary Directory
        run: |
          mkdir temp_publish_dir
          cp -r ${{ env.BUILD_OUTPUT_PATH }}/* temp_publish_dir/
          touch temp_publish_dir/yarn.lock

      - name: Publish to NPM
        working-directory: ./temp_publish_dir
        # run: yarn npm publish --tag latest
        run: yarn pack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
