name: Test Source Resolver

on:
  push:
    branches:
      - jb-fix-build

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: yarn --immutable

      - name: Build
        run: yarn build
