name: ABI Wasm test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHED_PATH: /tmp/nix-cache

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build noirc-abi-wasm
        run: |
          nix build -L .#noirc-abi-wasm
          cp -r ./result/noirc-abi-wasm/nodejs ./tooling/noirc-abi-wasm
          cp -r ./result/noirc-abi-wasm/web ./tooling/noirc-abi-wasm

      - name: Dereference symlink
        run: echo "UPLOAD_PATH=$(readlink -f ./result/noirc-abi-wasm)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: noirc-abi-wasm
          path: ${{ env.UPLOAD_PATH }}
          retention-days: 10

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download wasm package artifact
        uses: actions/download-artifact@v3
        with:
          name: noirc-abi-wasm
          path: ./tooling/noirc-abi-wasm

      - name: Install Yarn dependencies
        uses: ./.github/actions/setup

      - name: Run node tests
        run: yarn workspace @noir-lang/noirc-abi test

      - name: Install Playwright
        uses: ./.github/actions/install-playwright

      - name: Run browser tests
        run: yarn workspace @noir-lang/noirc-abi test:browser

