name: Test Workflow

on:
  push:
    branches:
      - jb-fix-build

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.67.0

      - name: Install cargo and wasm-bindgen
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install -f wasm-bindgen-cli --version 0.2.86

      - name: Install toml2json
        run: |
          source $HOME/.cargo/env
          cargo install toml2json

      - name: Build
        run: yarn build
