name: Wasm

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Wasm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.66.0

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm crate
        working-directory: ./crates/wasm
        run: ./build-wasm

      - name: Checkout noir-wasm-testing
        uses: actions/checkout@v3
        with:
          repository: noir-lang/noir-wasm-testing
          path: noir-wasm-testing

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Inject built wasm into noir-wasm-testing
        run: |
          cp -r ./crates/wasm/pkg ./noir-wasm-testing/noir_wasm
          jq '.dependencies.noir_wasm = "file:./noir_wasm"' ./noir-wasm-testing/package.json > ./noir-wasm-testing/package.json.tmp
          mv ./noir-wasm-testing/package.json.tmp ./noir-wasm-testing/package.json

      - name: Install dependencies and run tests
        working-directory: ./noir-wasm-testing
        run: |
          yarn install
          yarn test
