name: Wasm

on:
  push:
    branches:
      - jb/noir-testing-workflow
      - tom/noir-wasm-testing

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wasm package
        run: |
          nix build -L .#wasm

      - name: Checkout noir-wasm-testing
        uses: actions/checkout@v3
        with:
          repository: noir-lang/noir-wasm-testing
          ref: use-injected-nargo
          path: noir-wasm-testing

      - name: Inject built wasm into noir-wasm-testing
        run: |
          mkdir ./noir-wasm-testing/@noir-lang_noir_wasm
          cp -r -L ./result/* ./noir-wasm-testing/@noir-lang_noir_wasm
          jq '.dependencies["@noir-lang/noir_wasm"] = "file:./@noir-lang_noir_wasm"' ./noir-wasm-testing/package.json > ./noir-wasm-testing/package.json.tmp
          mv ./noir-wasm-testing/package.json.tmp ./noir-wasm-testing/package.json

      - name: Install nargo
        run: | 
          nix build .
          echo ./result/bin" >> $GITHUB_PATH

      - name: Run build.sh in noir-wasm-testing
        working-directory: ./noir-wasm-testing
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Install dependencies
        working-directory: ./noir-wasm-testing
        run: npm install

      - name: Run tests
        working-directory: ./noir-wasm-testing
        run: npm test
